### ISSUE TITLE
Unable to import decode_flac in 0.12.0 nor 0.11.0

### ISSUE THREAD

**Issue by gabrieltnishimura** [tensorflow/io#936] opened 2020-05-04 17:43 UTC
**Issue**: `decode_flac` function not available in 0.12.0 release.

Enviroment information
- **Python version**: 3.6.10
- **tensorflow version**: 2.1.0
- **tensorflow-io version**: 0.12.0

Code to reproduce:

```import tensorflow_io.core.python.experimental.audio_ops as ops```
```dir(ops)```

Returns:

```['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'absolute_import', 'core_ops', 'division', 'print_function', 'resample']```

But should contain:

```[..., 'decode_flac', ...] ```

It is neither contained in `tfio.experimental.audio.decode_flac` as described by https://github.com/tensorflow/io/commit/d1307e92b3da2bd6db45788e7a75b1e3e0cf1cc4.

**Comment by yongtang** [comment] 2020-05-04 17:51
@gabrieltnishimura The commit d1307e9 is merged after the release of v0.12.0. As such it is only available in nightly build at the moment (`python3 -m pip install tensorflow-io-nightly`).

We will be releasing a v0.13.0 once TF 2.2.0 final is out (TF 2.2.0 is currently in `rc4` and I am expecting a release of final in a week if no further release candidates). After that you can use tensorflow-io v0.13.0 for that.

**Comment by gabrieltnishimura** [comment] 2020-05-04 18:14
Thank you!
I'm also having issues with the nightly build. Upgrading all packages to:

 - **tensorflow version**: 2.2.0rc4
 - **tensorflow-io version**: 0.13.0.dev20200501181743

**Issue**: I can't seem to find anything under `tensorflow_io`.

**Code to reproduce**:

```import tensorflow_io```
```dir(tensorflow_io)```

**Returns**:

```['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']```

**Should return**:

Modules such as `core`.

**Comment by yongtang** [comment] 2020-05-04 19:15
@gabrieltnishimura I don't see a problem from a fresh install of tensorflow-io-nightly on Ubuntu 18.04:
```
# python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_io    
2020-05-04 19:13:03.593985: W tensorflow_io/core/kernels/audio_video_mp3_kernels.cc:252] libmp3lame.so.0 or lame functions are not available
2020-05-04 19:13:03.594301: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: AVX2 FMA
>>> dir(tensorflow_io)
['IODataset', 'IOTensor', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'audio', 'core', 'experimental', 'genome', 'image', 'v0', 'version']
>>> tensorflow_io.version.VERSION
'0.13.0'
>>> tensorflow_io.audio.decode_flac
<function decode_flac at 0x7f0e226b32f0>
>>> 
```

Can you specify the environment (Windows, Linux, macOS), pip?

**Comment by gabrieltnishimura** [comment] 2020-05-05 12:27
I'm using:
- **macOS**: 10.14.6
- **pip**: 20.0.2

**Comment by yongtang** [comment] 2020-05-07 04:51
@gabrieltnishimura Sorry for the late reply. The issue is likely caused by the fact that the binary we built on GitHub CI is with macOS Catalina and your local machine is 10.14?

In theory it should be possible to adjust the GitHub CI to build with passing additional flags to build against 10.14.

I will try to take a look tomorrow.

**Comment by yongtang** [comment] 2020-05-08 18:51
@gabrieltnishimura The issue was that, while we pass  `-mmacosx-version-min=10.13` in c++,
 the swift was not covered (need `-target x86_64-apple-macosx10.13`).

Added a PR #953 for the fix. Once merged you can give new nightly build a try (and we will release v0.13.0 very soon).

**Closed** 2020-05-08 20:52 UTC

**Comment by gabrieltnishimura** [comment] 2020-05-08 23:28
@yongtang sorry but I still have the same issue using

```
(tfio_test) ❯ pip list | grep tensorflow
tensorflow             2.2.0rc4
tensorflow-estimator   2.2.0
tensorflow-io-nightly  0.13.0.dev20200508175127
```

Is this the latest from nightly? I think the same error occured:

```
>>> import tensorflow_io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/__init__.py", line 17, in <module>
    from tensorflow_io.core.python.api.v0 import *  # pylint: disable=wildcard-import
  File "/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/api/v0/__init__.py", line 18, in <module>
    from tensorflow_io.core.python.ops.io_dataset import IODataset
  File "/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/__init__.py", line 71, in <module>
    core_ops = _load_library("libtensorflow_io.so")
  File "/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/__init__.py", line 67, in _load_library
    + "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs)
NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so']
caused by: ['dlopen(/Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so, 6): Symbol not found: _$sSo16CMBlockBufferRefa9CoreMedia01_aB14InitTrampolineACWP\n  Referenced from: /Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so\n  Expected in: /usr/lib/swift/libswiftCoreMedia.dylib\n in /Users/gabriel.t.nishimura/miniconda3/envs/usp/lib/python3.6/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so']
```

**Comment by yongtang** [comment] 2020-05-09 01:35
@gabrieltnishimura Sorry, the commit is 0a924ff, however, due to a GitHub CI issue, it does not create a new nightly yet. As you could see there is a red `X` on the left side.

The fix for the GitHub issue is in 824251a, which is currently running (brown dot on the left side). Once it successfully finish the nightly build will be populated to pypi.org.

**Comment by yongtang** [comment] 2020-05-09 01:44
@gabrieltnishimura to be more specific, the related GitHub CI status page is in https://github.com/tensorflow/io/runs/658146066 if it finished with every button green then the nightly build is pushed to PyPI.org.

**Comment by yongtang** [comment] 2020-05-09 04:12
@gabrieltnishimura The latest nightly `pip install tensorflow-io-nightly==0.13.0.dev20200509013058` is available now:
https://pypi.org/project/tensorflow-io-nightly/0.13.0.dev20200509013058/

**Comment by gabrieltnishimura** [comment] 2020-05-13 13:24
@yongtang thanks, the latest 0.13.0 fixes the problem as well!
