### ISSUE TITLE
Assertion failed error when reading Tiff image

### ISSUE THREAD

**Issue by gdrolet** [tensorflow/io#1171] opened 2020-11-04 18:31 UTC
I have 4-bands GeoTiff images I want to read into Tensors and ultimately into a tf.data.Dataset.

My kernel crashes with the following message: 

`Assertion failed: sizeof(tmsize_t)==sizeof(void*), file external/libtiff/libtiff/tif_open.c, line 99`

Here is the code that causes the crash:

```
import tensorflow as tf  # version 2.3.1
import tensorflow_io as tfio  # version 0.16.1

tiff_file = r"h:\data\images\39963ad1f4b053fa.tif"
image = tf.io.read_file(tiff_file)
tfio.experimental.image.decode_tiff(image, index=0)

```
My code runs in an anaconda environment (conda version 4.9.0) on Windows 10. 
Python version 3.8.3.
Tensorflow and tensorflow-io were installed using pip. 
No error pops up when loading tf/tfio. 
I can use other tf.data functionalities without problem.

**Comment by yongtang** [comment] 2020-11-05 23:15
Created a PR #1174 for the fix. I don;'t have a windows machine though it looks like #1174 should fix the issue.

**Comment by yongtang** [comment] 2020-11-06 15:43
@gdrolet A new nightly build has been released https://pypi.org/project/tensorflow-io-nightly/0.17.0.dev20201106135047/

I think this will address the Windows assertion failure for TIFF. Can you give it a try with:
```
pip install tensorflow-io-nightly==0.17.0.dev20201106135047
```

and let us know if the issue will be fixed?

**Comment by gdrolet** [comment] 2020-11-06 20:04
@yongtang Thanks for working on a fix. Unfortunately that didn't work.

I created a new environment to test the latest version of tensorflow-io:

```
conda create --name tfio python=3.8.6
conda activate tfio
pip install 
tensorflow-io-nightly==0.17.0.dev20201106135047
```
tf and tf-io versions are now 2.4.0-rc0 and 0.17.0

Running the same code as in my original post produces the same behaviour (kernel crash) and error message.

**Comment by yongtang** [comment] 2020-11-06 23:37
@gdrolet If possible can you provide a sample of the tiff file that triggers the crash?

I noticed you are referring to GeoTiff so I might be able to find some clue but a sample will definitely help a lot.

**Comment by gdrolet** [comment] 2020-11-07 02:07
@yongtang you will find the file here (expires in 24h):

https://transfert.mffp.gouv.qc.ca/?ShareToken=36FE7701AA7A7918B8F4D2B6930A7038C6D90325

**Comment by yongtang** [comment] 2020-11-08 10:15
@gdrolet A new version of tensorflow-io-nightly is now available (https://pypi.org/project/tensorflow-io-nightly/0.17.0.dev20201108041428/):
```
pip install tensorflow-io-nightly==0.17.0.dev20201108041428
```

I think the issue is now fixed. Can you give it a try?

**Comment by gdrolet** [comment] 2020-11-09 12:27
@yongtang it works! Thanks a lot for your support.

**Comment by yongtang** [comment] 2020-11-09 21:34
@gdrolet Glad the issue has been resolved.

**Closed by yongtang** 2020-11-09 21:34 UTC
