### ISSUE TITLE
[tf.estimator] - Support for non eagerly executing contexts

### ISSUE THREAD

**Issue by nmatare** [tensorflow/io#873] opened 2020-03-24 01:33 UTC
Many tensorflow-io calls trigger an eager op to derive metadata before returning the tf.data.Dataset object. This prevents us from using io functions in non eagerly executed contexts -- like those often found with tf.estimators.

As per the tensorflow [docs](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator):

> Calling methods of Estimator will work while eager execution is enabled. However, the model_fn and input_fn is not executed eagerly, Estimator will switch to graph mode before calling all user-provided functions (incl. hooks), so their code has to be compatible with graph mode execution. Note that input_fn code using tf.data generally works in both graph and eager modes.

For example:

```
import os
import pandas as pd
import tensorflow as tf

import tensorflow_io as tf_io
assert tf_io.__version__ == '0.12.0'

COLUMNS = list('ABCD')
TEMP_DIR = '/tmp/test_df.pq'

df = pd.DataFrame(pd.np.random.randint(0,100, size=(100, 4)), columns=COLUMNS)
df.to_parquet(TEMP_DIR)

def pq_input_fn():
  print('\n Executing in:', tf.executing_eagerly(), '\n')
  return tf_io.v0.IODataset.from_parquet([TEMP_DIR])

assert  tf.executing_eagerly()  # yup, works fine
print(next(iter(pq_input_fn())))

regressor = tf.estimator.BaselineRegressor()
regressor.train(input_fn=pq_input_fn)   # nope, not executing eagerly 

os.remove(TEMP_DIR)

# Traceback (most recent call last):
#   File "ask.py", line 24, in <module>
#     regressor.train(input_fn=pq_input_fn)
#   File "**/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 374, in train
#     loss = self._train_model(input_fn, hooks, saving_listeners)
#   File "**/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1164, in _train_model
#     return self._train_model_default(input_fn, hooks, saving_listeners)
#   File "**/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
#     input_fn, ModeKeys.TRAIN))
#   File "**/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1028, in _get_features_and_labels_from_input_fn
#     self._call_input_fn(input_fn, mode))
#   File "**/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1119, in _call_input_fn
#     return input_fn(**kwargs)
#   File "ask.py", line 17, in pq_input_fn
#     return tf_io.v0.IODataset.from_parquet([TEMP_DIR])
#   File "**/lib/python3.7/site-packages/tensorflow_io/core/python/ops/io_dataset.py", line 284, in from_parquet
#     filename, columns=columns, internal=True)
#   File "**/lib/python3.7/site-packages/tensorflow_io/core/python/ops/parquet_dataset_ops.py", line 59, in __init__
#     columns = columns if columns is not None else columns_v.numpy()
# AttributeError: 'Tensor' object has no attribute 'numpy'
  File "**/lib/python3.7/site-packages/tensorflow_io/core/python/ops/parquet_dataset_ops.py", line 59, in __init__
    columns = columns if columns is not None else columns_v.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'
```

Are there any workarounds or plans to support calls to tensorflow-io functions when not executing eagerly?

**Comment by yongtang** [comment] 2020-03-24 02:03
@nmatare Yes we plan to support graph (non-eager) mode for all ops in tensorflow-io. We already have quite a few supported. For example, all audio ops, AudioIOTensor and AudioIODataet, and hdf5 are just some examples. Technically this is not a big challenge. The only hard requirement is that in graph mode, data types has to be provided by user. Other than that, shapes, meta data, etc all could be done through graph operations. It will take some time to get all supported though. We will try to speed up to get this done. /cc @BryanCutler  @terrytangyuan

**Comment by nmatare** [comment] 2020-03-24 02:14
Ahh, great looking forward to it! Thanks for the speedy response and helpful details.

**Comment by ingolfured** [comment] 2020-04-07 17:19
Great, I'm quite interested in this feature as well, especially the from_parquet path.

**Comment by yongtang** [comment] 2020-05-12 19:33
@nmatare  @ingolfured The issue is being addressed in #960

**Closed** 2020-05-14 19:35 UTC
Labels: feature

**Comment by yongtang** [comment] 2020-05-14 23:34
PR #960 has been merged. The latest nightly build `tensorflow-io-nightly` should have fixed this issue.

**Comment by nmatare** [comment] 2020-05-15 13:49
Thanks for adding this!
