### ISSUE TITLE
v0.7.0 fails to build

### ISSUE THREAD

**Issue by epolitis** [tensorflow/io#520] opened 2019-10-01 12:52 UTC
`ERROR: /v/tensorflow_io/bigtable/BUILD:83:1: C++ compilation of rule '//tensorflow_io/bigtable:bigtable_lib_cc' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/a7ecd8237744645c5d189c197108d6d2/execroot/org_tensorflow_io && \
  exec env - \
    PATH=/miniconda/envs/tfio-dev/bin:/miniconda/condabin:/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TF_HEADER_DIR=/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow_core/include \
    TF_SHARED_LIBRARY_DIR=/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow_core \
    TF_SHARED_LIBRARY_NAME=libtensorflow_framework.so.2 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/tensorflow_io/bigtable/_objs/bigtable_lib_cc/bigtable_lib.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/tensorflow_io/bigtable/_objs/bigtable_lib_cc/bigtable_lib.pic.o' -fPIC '-DPB_FIELD_32BIT=1' -DCARES_STATICLIB -iquote . -iquote bazel-out/k8-fastbuild/genfiles -iquote bazel-out/k8-fastbuild/bin -iquote external/com_github_googleapis_google_cloud_cpp -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_googleapis_google_cloud_cpp -iquote bazel-out/k8-fastbuild/bin/external/com_github_googleapis_google_cloud_cpp -iquote external/com_github_grpc_grpc -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_grpc_grpc -iquote bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc -iquote external/com_github_madler_zlib -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_madler_zlib -iquote bazel-out/k8-fastbuild/bin/external/com_github_madler_zlib -iquote external/com_github_nanopb_nanopb -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_nanopb_nanopb -iquote bazel-out/k8-fastbuild/bin/external/com_github_nanopb_nanopb -iquote external/com_github_cares_cares -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_cares_cares -iquote bazel-out/k8-fastbuild/bin/external/com_github_cares_cares -iquote external/boringssl -iquote bazel-out/k8-fastbuild/genfiles/external/boringssl -iquote bazel-out/k8-fastbuild/bin/external/boringssl -iquote external/com_google_protobuf -iquote bazel-out/k8-fastbuild/genfiles/external/com_google_protobuf -iquote bazel-out/k8-fastbuild/bin/external/com_google_protobuf -iquote external/com_google_googleapis -iquote bazel-out/k8-fastbuild/genfiles/external/com_google_googleapis -iquote bazel-out/k8-fastbuild/bin/external/com_google_googleapis -iquote external/local_config_tf -iquote bazel-out/k8-fastbuild/genfiles/external/local_config_tf -iquote bazel-out/k8-fastbuild/bin/external/local_config_tf -isystem external/com_github_grpc_grpc/include -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_grpc_grpc/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_madler_zlib -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_madler_zlib -isystem bazel-out/k8-fastbuild/bin/external/com_github_madler_zlib -isystem external/com_github_cares_cares -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_cares_cares -isystem bazel-out/k8-fastbuild/bin/external/com_github_cares_cares -isystem external/com_github_grpc_grpc/third_party/address_sorting/include -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_grpc_grpc/third_party/address_sorting/include -isystem bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/third_party/address_sorting/include -isystem external/boringssl/src/include -isystem bazel-out/k8-fastbuild/genfiles/external/boringssl/src/include -isystem bazel-out/k8-fastbuild/bin/external/boringssl/src/include -isystem external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/genfiles/external/com_google_protobuf/src -isystem bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src -isystem external/com_google_googleapis -isystem bazel-out/k8-fastbuild/genfiles/external/com_google_googleapis -isystem bazel-out/k8-fastbuild/bin/external/com_google_googleapis -isystem external/local_config_tf/include -isystem bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include -isystem bazel-out/k8-fastbuild/bin/external/local_config_tf/include '-D_GLIBCXX_USE_CXX11_ABI=0' '-std=c++11' -DNDEBUG -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow_io/bigtable/kernels/bigtable_lib.cc -o bazel-out/k8-fastbuild/bin/tensorflow_io/bigtable/_objs/bigtable_lib_cc/bigtable_lib.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/dataset.h:23:0,
                 from ./tensorflow_io/bigtable/kernels/bigtable_lib.h:23,
                 from tensorflow_io/bigtable/kernels/bigtable_lib.cc:16:
bazel-out/k8-fastbuild/genfiles/external/local_config_tf/include/tensorflow/core/framework/attr_value.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
`

**Comment by yongtang** [comment] 2019-10-21 12:19
@epolitis I could not reproduce the issue locally, though from the error message this looks like a mismatch of protoc. Can you try with newer version 0.9.0 and see if issue still exists?

**Comment by yongtang** [comment] 2019-12-17 17:01
@epolitis The latest version is 0.10.0 and we are planning to release 0.11.0 very soon (inline with TF 2.1 release). A lot of updates within those versions. Can you try building against the latest version and see if the issue still exist?

I will close this issue for now but feel free to re-open if the issue persist.

**Closed by yongtang** 2019-12-17 17:01 UTC
