### ISSUE TITLE
Parallel HDF5 loading causes mismatch between expected outputs

### ISSUE THREAD

**Issue by Svdvoort** [tensorflow/io#898] opened 2020-04-14 19:46 UTC
This is probably related to some other bugs related to HDF5 loading (most likely #867 and #745), when using tfio.IOTensor.from_hdf5 in a mapped dataset function, it will return wrong instances of the loaded data. Presumably, this is because of #867. Gave me a real head-scratcher, as my samples and features did not match, causing the network to not learn anything.

Example google collab is here: https://colab.research.google.com/drive/1uv8OKu5eHDNyyUr31sJci-ucTSb-l8WQ

Everything goes alright as long as num_parallel_calls=1, but goes wrong otherwise. 
Since no error is given, it can be quite hard to figure out that this is what causes everything to go wrong. 

Bug is present in tensorflow-io==0.12.0, as well as in tensorflow-io-nightly==0.13.0.dev20200412224010

**Comment by Svdvoort** [comment] 2020-04-15 12:32
I just saw #899, which I believed might solve the issue. I've installed the compiled wheel from that pr to try, but it seems like the issue is not resolved

**Comment by yongtang** [comment] 2020-04-17 01:47
@Svdvoort The Colab in your post is using `tfio.IODataset.from_hdf5` but in the post `tfio.IOTensor.from_hdf5` is mentioned. Wondering if this is correct? If the issue is related `tfio.IODataset.from_hdf5` then I think the issue should have been resolved in #899? Otherwise I may need to take another look.

**Comment by Svdvoort** [comment] 2020-04-17 05:12
Apologies, you're right I accidentally linked to the Colab from #867, this is the correct one: https://colab.research.google.com/drive/1iT75uFmb2Tni9tFr4PtsMsg6ju_yLUDb

**Comment by yongtang** [comment] 2020-04-20 16:55
@Svdvoort I more or less figured out the reason for the issue. It is a little complicated as it may impact other ops as well. Will try to fix it soon.

**Comment by yongtang** [comment] 2020-05-03 18:49
This issue is being fixed by #922

**Comment by yongtang** [comment] 2020-05-04 19:32
@Svdvoort The PR #922 has been merged and the latest tensorflow-io-nightly is available. I tried your Colab (with `pip install tensorflow-io` changed to `pip install tensorflow-io-nightly`) and it works fine now.

I will close this issue but feel free to reopen if issue persists.

**Closed by yongtang** 2020-05-04 19:32 UTC
Labels: bug

**Comment by Svdvoort** [comment] 2020-05-05 05:25
Thanks, the issue indeed seems to be resolved!
